config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  resources :events, except: :show   
end

app/models/event.rb
class Event < ActiveRecord::Base
  def self.this_week
    where(:created_at => (Date.today.beginning_of_week)..(Date.today.end_of_week))
  end

  def self.this_week_total
    this_week.inject(0) { |sum, e| sum + e.amount }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index 
    @events = Event.this_week
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find_by(params[:event_params])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_url
    else
      redirect_to action: "new"
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to root_url
    else
      redirect_to action: "edit"
    end
  end

  def destroy 
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_url
  end

  private 
  
  def event_params
    params.require(:event).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
  <%= f.submit "Update it!" %>
<% end %>

app/views/events/index.html.erb
<h1>Savings This Week</h1>
<div>
  <ul>
    <% @events.each do |event| %>
      <li><%= event.created_at.strftime("%b %d, %Y") %>: <%= event.name %> <%= number_to_currency(event.amount) %> <%= link_to "Edit", edit_event_path(event.id) %> | <%= link_to "Delete", { action: :destroy, id: event.id }, method: :delete %></li>
    <% end %>
  </ul>
</div>

<div>
  <strong>Total: <%= number_to_currency(Event.this_week_total) %></strong>
</div>

<div>
  <%= link_to "Add More Savings", new_event_path %>
</div>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
  <%= f.submit "Save(d) it!" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onebrokeb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>